== План оновлення перекладу

Поточний переклад базується на версії https://github.com/progit/progit2/commit/e95aba0b236ab57b8ea9a1ef1b4fdae6339573ec[e95aba0b236ab57b8ea9a1ef1b4fdae6339573ec]
(`english-version`) від 3-го квітня 2016-го року.

Це план, як оновити переклад до версії https://github.com/progit/progit2/commit/652208f3f9ba3f31a846cf54b4b1aa682dd72e09[2.1.434] від 4 вересня 2024-го року.

Спробував залити `2.1.434` до `master`, список файлів з конфліктами у `files.adoc`.

// Пропонований порядок роботи (продемонстрований на `book/01-introduction/sections/about-version-control.asc`):
// 
// Спершу отримаємо всі версії цього файлу:
//
// ----
// f=book/01-introduction/sections/about-version-control.asc
// # Дивимося конфлікти
// git show origin/english-version:$f > $f-old-english
// git show 2.1.434:$f > $f-cur-english
// git show HEAD:$f > $f-ukrainian
// git merge-file --diff3 -p $f-ukrainian $f-old-english $f-cur-english > $f
// rm $f-ukrainian $f-old-english $f-cur-english
// ----
//
// Виправляємо файл і робимо PR.

.Примітка
Якщо працюєте з власним відсадком, то не забудьте стягнути гілку `english-version` з оригінального репозиторію.
